
export interface Productos {
	img: string;
	title: string;
	tipo:string;
	tallas:string
	precio: string;
	flipImage?: boolean;
}



export const new_balance_productos = [
    { img:'/new-balance/New Balance-550.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/new-balance/New Balance-550-2.webp', title:'New Balance', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/new-balance/New Balance-550-3.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/new-balance/New Balance-550-4.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/new-balance/New Balance-550-5.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/new-balance/New Balance-550-6.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/new-balance/New Balance-7.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/new-balance/New Balance-8.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/new-balance/New Balance-9.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/new-balance/New Balance-10.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/new-balance/New Balance-11.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/new-balance/New Balance-12.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/new-balance/New Balance-13.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/new-balance/New Balance-14.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/new-balance/New Balance-16.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/new-balance/New Balance-17.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/new-balance/New Balance-18.webp', title:'New Balance', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
]

export const nike_productos = [
    {img:'/nike/zapatilla-nike(1).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (2).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (3).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (4).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (5).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (6).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (7).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (8).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (9).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (10).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (11).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (12).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (13).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (14).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (15).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (16).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (17).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (18).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (19).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (20).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (21).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (22).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (23).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (24).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (25).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (26).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (27).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},
    {img:'/nike/zapatilla-nike (28).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (29).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (30).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (31).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (32).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (33).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (34).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (35).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (36).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (37).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (38).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (39).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (40).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (41).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (42).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (43).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (44).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (45).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (46).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (47).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (48).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (49).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (50).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (51).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (52).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (53).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (54).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (55).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (56).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (57).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (58).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (59).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (60).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (61).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (62).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (63).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (64).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (65).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (66).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (67).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (68).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (69).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (70).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (71).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (72).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (73).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (74).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (75).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (76).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (77).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (78).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (79).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (80).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (81).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (82).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (83).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (84).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (85).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (86).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (87).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (88).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (89).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (90).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (91).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (92).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (93).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (94).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (95).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (96).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (97).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (98).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (99).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (100).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (101).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (102).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (103).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (104).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (105).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (106).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (107).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (109).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (110).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (111).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (112).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (113).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (114).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (115).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (116).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (117).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (118).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (119).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (120).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (121).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
    {img:'/nike/zapatilla-nike (122).webp',title:'Nike',tipo:'Zapatillas',tallas:'Tallas 36/45',precio:'80€'},   
]

export const adidas_productos = [
    { img:'/adidas/adidas-1.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/adidas/adidas-2.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/adidas/adidas-3.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/adidas/adidas-4.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/adidas/adidas-5.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/adidas/adidas-6.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/adidas/adidas-7.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-8.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-9.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-10.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-11.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-12.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-13.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-14.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-16.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-17.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-18.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-19.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-20.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-21.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-22.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-23.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-24.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-25.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-26.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-27.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-28.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-29.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-30.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-31.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
    { img:'/adidas/adidas-32.webp', title:'Adidas', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€'},
]

export const converse_productos = [
    { img:'/converse/converse.webp', title:'Converse', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/converse/converse-1.webp', title:'Converse', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/converse/converse-2.webp', title:'Converse', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/converse/converse-3.webp', title:'Converse', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/converse/converse-4.webp', title:'Converse', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/converse/converse-5.webp', title:'Converse', tipo:'Zapatillas', tallas:'Tallas 36/45', precio:'80€',},
]

export const trapstar_productos = [
    { img:'/trapstar/Camisetas  (1).webp', title:'Trapstar', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Camisetas  (2).webp', title:'Trapstar', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Camisetas  (3).webp', title:'Trapstar', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Camisetas  (4).webp', title:'Trapstar', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Camisetas  (5).webp', title:'Trapstar', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Camisetas  (6).webp', title:'Trapstar', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Camisetas  (7).webp', title:'Trapstar', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Chandal-entero (1).webp', title:'Trapstar', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Chandal-entero (2).webp', title:'Trapstar', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Chandal-entero (3).webp', title:'Trapstar', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Chandal-entero (4).webp', title:'Trapstar', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Chandal-entero (5).webp', title:'Trapstar', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Chandal-entero (6).webp', title:'Trapstar', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Chaquetas  (1).webp', title:'Trapstar', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Chaquetas  (2).webp', title:'Trapstar', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Chaquetas  (3).webp', title:'Trapstar', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Chaquetas  (4).webp', title:'Trapstar', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Sudadera.webp', title:'Trapstar', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Sudaderas (1).webp', title:'Trapstar', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Sudaderas (2).webp', title:'Trapstar', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Sudaderas (3).webp', title:'Trapstar', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/trapstar/Sudaderas (4).webp', title:'Trapstar', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
]

export const dolce_and_gabbana_productos = [
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Airmaster Blue.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Airmaster Multicolor.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Daymaster Beige.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Daymaster Pool Blue.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Portofino Black Silver.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Portofino Black.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Portofino Strapped Black.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Portofino Strapped Red.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Portofino Strapped White.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Portofino White Black.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Portofino White Gold.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/zapatillas/Dolce & Gabbana Portofino White.webp', title:'Dolce & Gabbana', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (1).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (2).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (3).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (4).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (5).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (6).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (7).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (8).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (9).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (10).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (11).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (12).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (13).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (14).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (15).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (16).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (17).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (18).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (19).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (20).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (21).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (24).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (25).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (26).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (27).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (28).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (29).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (30).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Camisetas (31).webp', title:'Dolce & Gabbana', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Chandal (1).webp', title:'Dolce & Gabbana', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Chandal (2).webp', title:'Dolce & Gabbana', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Chandal (3).webp', title:'Dolce & Gabbana', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Sudaderas-Jerseys (1).webp', title:'Dolce & Gabbana', tipo:'Sudaderas/Jerseys', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Sudaderas-Jerseys (2).webp', title:'Dolce & Gabbana', tipo:'Sudaderas/Jerseys', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Sudaderas-Jerseys (3).webp', title:'Dolce & Gabbana', tipo:'Sudaderas/Jerseys', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Sudaderas-Jerseys (4).webp', title:'Dolce & Gabbana', tipo:'Sudaderas/Jerseys', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Sudaderas-Jerseys (5).webp', title:'Dolce & Gabbana', tipo:'Sudaderas/Jerseys', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Sudaderas-Jerseys (6).webp', title:'Dolce & Gabbana', tipo:'Sudaderas/Jerseys', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Sudaderas-Jerseys (7).webp', title:'Dolce & Gabbana', tipo:'Sudaderas/Jerseys', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Sudaderas-Jerseys (8).webp', title:'Dolce & Gabbana', tipo:'Sudaderas/Jerseys', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Sudaderas-Jerseys (9).webp', title:'Dolce & Gabbana', tipo:'Sudaderas/Jerseys', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Sudaderas-Jerseys (10).webp', title:'Dolce & Gabbana', tipo:'Sudaderas/Jerseys', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/dolce-and-gabbana/Sudaderas-Jerseys (11).webp', title:'Dolce & Gabbana', tipo:'Sudaderas/Jerseys', tallas:'Tallas 36/45', precio:'80€',},
]

export const balenciaga_productos = [
    
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (1).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (2).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (3).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (4).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (5).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (6).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (7).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (8).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (9).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (10).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (11).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (12).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/zapatilla/Balenciaga-zapatillas (13).webp', title:'Balenciaga', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (1).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (2).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (3).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (4).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (5).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (6).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (7).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (8).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (9).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (10).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (11).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (12).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (13).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (14).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (15).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (16).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (17).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (18).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (19).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (20).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (21).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (22).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (23).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (24).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (25).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (26).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (27).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (28).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (29).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (30).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (31).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (32).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (33).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (34).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (35).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Camisetas (36).webp', title:'Balenciaga', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (1).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (2).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (3).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (4).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (5).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (6).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (7).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (8).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (9).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (10).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (11).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (12).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (13).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (14).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (15).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Chandal (16).webp', title:'Balenciaga', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (1).webp', title:'Balenciaga', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (2).webp', title:'Balenciaga', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (3).webp', title:'Balenciaga', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (4).webp', title:'Balenciaga', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (5).webp', title:'Balenciaga', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (6).webp', title:'Balenciaga', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (7).webp', title:'Balenciaga', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (8).webp', title:'Balenciaga', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (9).webp', title:'Balenciaga', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (10).webp', title:'Balenciaga', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (1).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (2).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (3).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (4).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (5).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (6).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (7).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (8).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (9).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (10).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (11).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (12).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (13).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (14).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (15).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (16).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (17).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (18).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (19).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (20).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (21).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (22).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (23).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (24).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (25).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (26).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (27).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (28).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (29).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (30).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (31).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (32).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (33).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (34).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (35).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (36).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (37).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/balenciaga/Sudaderas-jerseys (38).webp', title:'Balenciaga', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
]

export const golden_goose_stardan_productos = [
    
    { img:'/golden-goose-stardan/zapatilla-golden-goose (1).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (2).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (3).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (4).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (5).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (6).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (7).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (8).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (9).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (10).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (11).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (12).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (13).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (14).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (15).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (16).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (17).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (18).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (19).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (20).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (21).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (24).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (25).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (26).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (27).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (28).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (29).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/golden-goose-stardan/zapatilla-golden-goose (30).webp', title:'Golden Goose Stardan', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    
]

export const versace_productos = [
    
    { img:'/versace/versace-zapatilla-1.webp', title:'Versace', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-zapatilla-2.webp', title:'Versace', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-zapatilla-3.webp', title:'Versace', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-zapatilla-4.webp', title:'Versace', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-zapatilla-5.webp', title:'Versace', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-zapatilla-6.webp', title:'Versace', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-1.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-2.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-3.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-4.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-5.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-6.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-7.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-8.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-9.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-10.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-11.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-12.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-13.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-14.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-15.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-16.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-17.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-18.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-19.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-20.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-21.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-22.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/versace-23.webp', title:'Versace', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/sudadera-versace (1).webp', title:'Versace', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/sudadera-versace (2).webp', title:'Versace', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/sudadera-versace (3).webp', title:'Versace', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/sudadera-versace (4).webp', title:'Versace', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/sudadera-versace (5).webp', title:'Versace', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/versace/sudadera-versace (6).webp', title:'Versace', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},   
]

export const louboutin_productos = [
    { img:'/louboutin/Louboutin-1.webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/louboutin/Louboutin-2.webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/louboutin/Louboutin-3.webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/louboutin/Louboutin-4.webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/louboutin/Louboutin-5.webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/louboutin/Louboutin-6.webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/louboutin/Louboutin-7.webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
]

export const alexander_McQueen = [
    
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (1).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (2).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (3).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (4).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (5).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (6).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (7).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (8).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (9).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (10).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (11).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (12).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (13).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/alexander-mcqueen/zapatilla-alexander-mcqueen (14).webp', title:'Louboutin', tipo:'Zapatilla', tallas:'Tallas 36/45', precio:'80€',},
]

export const the_north_face_productos = [

    { img:'/the-north-face/Camisetas (1).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (3).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (4).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (5).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (6).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (7).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (8).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (9).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (10).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (11).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (13).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (14).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (15).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (16).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (17).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Camisetas (18).webp', title:'The North Face', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Pantalones (1).webp', title:'The North Face', tipo:'Pantalone', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Pantalones (2).webp', title:'The North Face', tipo:'Pantalone', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (1).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (2).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (3).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (4).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (5).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (6).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (7).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (8).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (9).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (10).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (11).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (12).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas  (13).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (15).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (16).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (17).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (18).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (19).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (20).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (21).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (22).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (23).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (24).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (25).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (26).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (27).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (28).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (29).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/the-north-face/Sudaderas (30).webp', title:'The North Face', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    
]

export const prada_productos = [

    { img:'/prada/Camisetas (1).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (2).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (3).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (4).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (5).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (6).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (7).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (8).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (9).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (10).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (11).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (12).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (13).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (14).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (15).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (16).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (17).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (18).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (19).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (20).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (21).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (22).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (23).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (24).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (25).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (26).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (27).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (28).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (29).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (30).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (31).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (32).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (33).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (34).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (35).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (36).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (37).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (38).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (39).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (40).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (41).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (42).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (43).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (44).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (45).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (46).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (47).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (48).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (49).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (50).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (51).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (52).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (53).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (54).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (55).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (56).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (57).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (58).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (59).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (60).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (61).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (62).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Camisetas (63).webp', title:'Prada', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chandal (1).webp', title:'Prada', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chandal (2).webp', title:'Prada', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chandal (3).webp', title:'Prada', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chandal (4).webp', title:'Prada', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chaquetas (1).webp', title:'Prada', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chaquetas (2).webp', title:'Prada', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chaquetas (3).webp', title:'Prada', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chaquetas (4).webp', title:'Prada', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chaquetas (5).webp', title:'Prada', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chaquetas (6).webp', title:'Prada', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chaquetas (7).webp', title:'Prada', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chaquetas (8).webp', title:'Prada', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Chaquetas (9).webp', title:'Prada', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (1).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (2).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (3).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (4).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (5).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (6).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (7).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (8).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (9).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (10).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (11).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (12).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (13).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (14).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (15).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (16).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (17).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (18).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (19).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (20).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (21).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (22).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (23).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (24).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (25).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (26).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (27).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (28).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (29).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (30).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (31).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (32).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (33).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (34).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (35).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (36).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (37).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/prada/Sudaderas-jerseys (38).webp', title:'Prada', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
]

export const palm_angels_productos = [

    { img:'/palm-angels/camiseta (1).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (2).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (3).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (4).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (5).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (6).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (7).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (8).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (9).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (10).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (11).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (12).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (13).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (14).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (15).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (16).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (17).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (18).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (19).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (20).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (21).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (22).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (23).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (24).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (25).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (26).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (27).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (28).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (29).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (30).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (31).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (32).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (33).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (34).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (35).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (36).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (37).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (38).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (39).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (40).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (41).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (42).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (43).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (44).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (45).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (46).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (47).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (48).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (49).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (50).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (51).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (52).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (53).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (54).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (55).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (56).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (57).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (58).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (59).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (60).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/camiseta (61).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/chandal (1).webp', title:'Palm Angels', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/chandal (2).webp', title:'Palm Angels', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/chandal (3).webp', title:'Palm Angels', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/chandal (4).webp', title:'Palm Angels', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/chandal (5).webp', title:'Palm Angels', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/chandal (6).webp', title:'Palm Angels', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/chandal (7).webp', title:'Palm Angels', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/chandal (8).webp', title:'Palm Angels', tipo:'Chandal', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/chaqueta.webp', title:'Palm Angels', tipo:'Chaqueta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/pantalon (1).webp', title:'Palm Angels', tipo:'Pantalon', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/pantalon (2).webp', title:'Palm Angels', tipo:'Pantalon', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/pantalon (3).webp', title:'Palm Angels', tipo:'Pantalon', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/pantalon (4).webp', title:'Palm Angels', tipo:'Pantalon', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/pantalon (5).webp', title:'Palm Angels', tipo:'Pantalon', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/pantalon (6).webp', title:'Palm Angels', tipo:'Pantalon', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/pantalon (7).webp', title:'Palm Angels', tipo:'Pantalon', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/pantalon (8).webp', title:'Palm Angels', tipo:'Pantalon', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/pantalon (9).webp', title:'Palm Angels', tipo:'Pantalon', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/short.webp', title:'Palm Angels', tipo:'Short', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/short (2).webp', title:'Palm Angels', tipo:'Short', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (1).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (2).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (3).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (4).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (5).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (6).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (7).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (8).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (9).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (10).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (11).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (12).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (13).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (14).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (15).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (16).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (17).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/palm-angels/sudadera (18).webp', title:'Palm Angels', tipo:'Sudadera', tallas:'Tallas 36/45', precio:'80€',},
]

export const off_white_productos = [

    { img:'/off-white/Camisetas-OFF-WHITE (1).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (2).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (3).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (4).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (5).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (6).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (7).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (8).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (9).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (10).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (11).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (12).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (13).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (14).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (15).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
    { img:'/off-white/Camisetas-OFF-WHITE (16).webp', title:'Palm Angels', tipo:'Camiseta', tallas:'Tallas 36/45', precio:'80€',},
]